kind: Service
apiVersion: v1
metadata:
  labels:
    app: resin-cms-interviews
  name: resin-cms-interviews
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: resin-cms-interviews
